controller_manager:

  ros__parameters:
    update_rate: 10
  # Publish all joint states -----------------------------------
  joint_state_broadcaster:
    type: joint_state_broadcaster/JointStateBroadcaster
    publish_rate: 50

  # Position Controllers --------------------------------------
  Revolute 6_position_controller:
    type: effort_controllers/JointPositionController
    joint: Revolute 6
    pid: {p: 100.0, i: 0.01, d: 10.0}
  Revolute 7_position_controller:
    type: effort_controllers/JointPositionController
    joint: Revolute 7
    pid: {p: 100.0, i: 0.01, d: 10.0}
  Revolute 37_position_controller:
    type: effort_controllers/JointPositionController
    joint: Revolute 37
    pid: {p: 100.0, i: 0.01, d: 10.0}
  Revolute 38_position_controller:
    type: effort_controllers/JointPositionController
    joint: Revolute 38
    pid: {p: 100.0, i: 0.01, d: 10.0}
  Revolute 39_position_controller:
    type: effort_controllers/JointPositionController
    joint: Revolute 39
    pid: {p: 100.0, i: 0.01, d: 10.0}
  Revolute 40_position_controller:
    type: effort_controllers/JointPositionController
    joint: Revolute 40
    pid: {p: 100.0, i: 0.01, d: 10.0}
  Revolute 41_position_controller:
    type: effort_controllers/JointPositionController
    joint: Revolute 41
    pid: {p: 100.0, i: 0.01, d: 10.0}
  Revolute 42_position_controller:
    type: effort_controllers/JointPositionController
    joint: Revolute 42
    pid: {p: 100.0, i: 0.01, d: 10.0}

